In [1]:
import numpy as np
import scipy.linalg as la

In [3]:
a = np.array([1,3,-2,1])

In [9]:
'''
    Number of dimensions ndim. Shape returns a tuple.
    Size returns the number of elements in matrix
'''
dim = a.ndim
shape = a.shape
size = a.size
print(dim)
print(shape)
print(size)

1
(4,)
4


In [12]:
'''
    Create a 2D array in numpy
'''
M = np.array([[1,2],[3,7],[-1,5]])
M

array([[ 1,  2],
       [ 3,  7],
       [-1,  5]])

In [17]:
M.ndim,M.shape, M.size

(2, (3, 2), 6)

In [28]:
col = M[:,1]
col

array([2, 7, 5])

In [31]:
col.ndim, col.shape, col.size

(1, (3,), 3)

In [37]:
'''
    Reshaping into a column vector of dim 3X1.
    Very useful
'''
column = col.reshape(3,1)
column

array([[2],
       [7],
       [5]])

In [38]:
column.ndim, column.shape, column.size

(2, (3, 1), 3)

In [41]:
b = np.array([[1,3], [2,5]])

In [44]:
'''
    Element-wise multiplication
'''
b*b

array([[ 1,  9],
       [ 4, 25]])

In [51]:
b@b

array([[ 7, 18],
       [12, 31]])

In [58]:
'''
    Example
'''
i = np.array([[1,0],[0,1]])
a = np.array([[1,3],[-1,7]])
b = np.array([[5,2], [1,2]])

print (2*i + 3*a - a@b)

[[-3  1]
 [-5 11]]


In [63]:
'''
    Matrix Power. Use numpy.linalg.matrix_power.
    No separate import required
'''
M = np.array([[3,4], [-1,5]])
np.linalg.matrix_power(M,52)

array([[ 1805995961,  2026127936],
       [-1580273808,   671576281]])

In [64]:
'''
    Transpose
'''
M.T

array([[ 3, -1],
       [ 4,  5]])

In [67]:
'''
    Inverse
'''
np.linalg.inv(M)

array([[ 0.26315789, -0.21052632],
       [ 0.05263158,  0.15789474]])

In [68]:
'''
    Trace - sum of all the elements in the main diagonal
'''
np.trace(M)

8

In [71]:
np.linalg.det(M)

18.999999999999996